version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nairobi_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  pgdata:
    name: nairobi_db_volume

networks:
  app-network:
    driver: bridge
    name: nairobi_app_network