FROM python:3.10-slim

WORKDIR /app

COPY processing/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY processing/ ./processing/

WORKDIR /app/processing

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
